RedHatInsights/ansible-collections-insights

.github/workflows/ansible-test.yml, .github/workflows/galaxy-release.yml, CHANGELOG.md, README.md, docs/create_docs.yml, docs/inventory.md, docs/templates/inventory.md.j2, plugins/inventory/insights.py, release.yml, tests/inventory/insights.yml
This update to the insights inventory plugin adds an option to pull patching information from insights service to create additional host vars. The additional variables added are:
```
insights_patching:
enabled: true|false
last_evaluation: time/date
last_upload: time/date
rhba_count: bug advisory count
rhea_count: enhancement advisory count
rhsa_count: security advisory count
stale: true|false
```
This data can be used to create groups as shown in `tests/inventory/insights.yml`. The `groups` sections will compose groups based on host var conditions. The following example will create a group for each type of advisory
```
groups:
bug_patch: insights_patching.rhba_count > 0
security_patch: insights_patching.rhsa_count > 0
enhancement_patch: insights_patching.rhea_count > 0  
```
Additional …
=> Get Patches

roles/compliance/README.md, roles/compliance/meta/main.yml, roles/compliance/tasks/install.yml, roles/compliance/tasks/main.yml, roles/compliance/tasks/run.yml, roles/compliance/tests/compliance.yml, roles/compliance/tests/install-only.yml, roles/compliance/tests/run-only.yml
Add a role to run Insights compliance scans. It can be used to install required packages and run OpenSCAP scan.
=> Compliance Role

plugins/inventory/insights.py
This PR addresses issue #5 where the `ansible_host` variable from Insights was always set as `ansible_host` variable in inventory. This causes conflict when using multiple inventory sources and did not allow the user to control which source defines `ansible_host`. For example, if using an inventory from aws which would allow the user to choose the public or private IP for the value of `ansible_host` it would conflict or be overridden by the Insights inventory.
=> ansible_host variable

plugins/modules/insights_register.py
There was no default set for `force_reregister` in the docs, so I added it for the sanity tests.
Signed-off-by: Stephen Adams <tsadams@gmail.com>
=> fix(docs): Set proper defaults for force_reregister

plugins/inventory/insights.py
This ensures all inventory hosts out of the box are addressable.
Without this, a host returned by the plugin with a display name of "Joe's Server" would fail when used in a playbook.
Remediation playbooks appear to use this fqdn value in their `hosts` line as well, so we should ensure it is used.
=> Map the `fqdn` var to ansible_hostname

bindep.txt, requirements.txt
Testinfra isn't needed by the collections direct, but for testing. We
can remove it from the final image of EEs.
We can also install python38-requests from the distro RPM packages, so
lets add that too.
Signed-off-by: Paul Belanger <pabelanger@redhat.com>
=> Remove testinfra / add bindep.txt file

galaxy.yml.j2, plugins/inventory/insights.py
Hi,
I tested in my environment and this would solve https://github.com/RedHatInsights/ansible-collections-insights/issues/25
Error:
```
No connection adapters were found for '/api/patch/v1/systems?offset=20&limit=20&filter[stale]=eq:True&sort=-last_upload'"
```
Error happens when iterating for next page (https://github.com/RedHatInsights/ansible-collections-insights/blob/master/plugins/inventory/insights.py#L123), the var "url" gets overwritten by the "next_page" var, which does not include  the scheme "https" and the server name "console.redhat.com" , and so this makes the HTTP request fail. 
In order to solve this, I suggest concatenating scheme and server by doing following slight modification: https://github.com/RedHatInsights/ansible-collections-insights/pull/29/files#diff-c5612de53a1 …
=> add scheme and server

plugins/inventory/insights.py
Fixes #28. Tested in ansible 2.12 CLI and AAP 2.1 EE.
=> issue 28 get_tags fix

roles/insights_client/tasks/main.yml
These two tasks cannot work properly without `become: true`.  
That's all this pull request does.
=> Sets become to true for 'Deploy Custom Tags' and 'Remove Tags' tasks

plugins/inventory/insights.py
fixes - https://github.com/RedHatInsights/ansible-collections-insights/issues/48 
This can be improved more but here is a quick fix. Basically URL is generating incorrectly. We are appending to the same old url because of which url gets bigger than 4096 characters.
Example - 
```
https://console.redhat.com/api/inventory/v1/hosts?&page=2&page=3&page=4&page=5&page=6&page=7&page=8&page=9&page=10&page=11
```
=> Fixes #RHINENG-765 - fixed incorrectly generating url

.github/dependabot.yml, .github/workflows/ansible-test.yml, meta/runtime.yml, plugins/inventory/insights.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt
The current CI (the sanity test, in particular) is broken:
- some actions changed behaviour and do not work anymore
- the latest runners are too new for certain versions of Ansible & Python
- and few more problems
To fix this, massage a bit the existing code and CI bits:
- consider Ansible 2.12 as supported; it was already supposed to be tested, so most likely it was intended to be supported
- remove a Python 3.5+ bit, making all the bits usable with Python 2.7+
- fix pylint issues: whitespace issues, long lines
- update the ignores for the sanity test to match the current situation
- do not run CI jobs on push for branches different than `master`, leaving them only for PR events
- update the already used actions to latest versions
- allow all the jobs to run, instead of cancelling all …
=> CI: update & fix to run properly

.github/workflows/ansible-test.yml, meta/runtime.yml, plugins/inventory/insights.py, plugins/modules/insights_register.py, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
Add support, even if tested only with sanity test, for Ansible versions from 2.9 (included) up to Ansible 2.15 (included).
The matrix of the support Ansible+Python combinations is taken from:
https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix
The additional changes are:
- fix the documentation of the inventory plugin a bit
- fix the default of the `display_name` parameter of the `insights_register` module
- add ignores for the missing GPLv3 header in the inventory plugin: the expectation of Ansible is that plugins are licensed as GPLv3, and
> the MAIN use of `ansible-test` is to test ansible-core
[1]
[1] https://github.com/ansible/ansible/issues/67032
=> Support more Ansible versions

.github/workflows/ansible-test.yml
Make sure that pushes to `master` actually trigger the `ansible-test` workflow; this was accidentally broken when limiting by using the more modern `main` instead.
Since renaming the branch to `main` might be possible in the future, add `master` without removing `main`.
Fixes commit dd2418a14538fd16f32a87ffbdcc1027677628d4
=> ci: restore the execution on push

.github/workflows/ansible-test.yml
When running the job on push, the checkout done by `actions/checkout` does not need to be tweaked for `ansible-community/ansible-test-gh-action`.
=> ci: checkout PR branch only for PRs

.github/scripts/jinja2-replace, .github/workflows/ansible-test.yml
It looks like the cuchi/jinja2-action action is currently broken [1]. Since all we need is to render a jinja2 template with string variables, then roll out a simple script Python using the "jinja2" module to do that.
The script adds to the render context all the environment variables starting with the prefix `JINJA_`, removing it.
The script does not have a ".py" extension on purpose, to avoid being picked by ansible-test.
[1] https://github.com/cuchi/jinja2-action/issues/17
=> ci: use own script for rendering a jinja2 template

plugins/inventory/insights.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
Do not assume that `requests` is available, as the importing error will
not be properly noticeable in most of the environments; this is also
checked by the sanity testing of Ansible [1].
Follow the recommended practice by storing the import error separately,
raising it as Ansible error when the plugin is used. This makes it
possible to drop all the ignores for this issue for the sanity test.
As related/needed change: drop the version check for `requests`: v1.1.0 is more than 10 years old, and even old distros have much higher versions than that. This also gets rid of `distutils`, so there will be less problems with Python 3.12+.
[1] https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/import.html
=> inventory: gracefully handle the lack of python-requests

meta/runtime.yml
Newer versions of Ansible should generally work fine, and in case there are issues they need to be fixed anyway.
=> feat: drop upper-limit Ansible requirement

plugins/modules/insights_register.py
As  @ptoscano noted during #55 , --force-reregister has been deprecated, and should be replaced by --unregister + --register.
This commit wants to introduce this logic, keeping the 'force_reregister' parameter, but using it to first unregister and then reregister if flagged.
=> fix: force-reregister deprecated

docs/insights_config.md, docs/insights_register.md, docs/inventory.md, plugins/inventory/insights.py, plugins/modules/insights_config.py, plugins/modules/insights_register.py
Some description lack of uppercase. Staleness used default instead of choices.
=> Fix docs description format

docs/create_docs.yml, release.yml, roles/compliance/tasks/install.yml, roles/compliance/tasks/main.yml, roles/compliance/tasks/run.yml, roles/compliance/tests/compliance.yml, roles/compliance/tests/install-only.yml, roles/compliance/tests/run-only.yml, roles/insights_client/tasks/main.yml, roles/insights_client/tests/example-insights-client-playbook.yml
Plays and tasks ought to be named by default, and ansible-lint warns about that too. Hence:
- add names to plays and tasks that did not have any
- fix the existing names so they start with an uppercase letter
=> chore: add/fix names of plays and tasks

.github/workflows/ansible-test.yml, CHANGELOG.md, plugins/inventory/insights.py
- revert commit 9916d9adba85c89a53fd7f91112b906e587f4a51, no more needed since Python 2.7 is not supported
- simplify the `ansible-test` CI workflow
=> Few cleanups after old Ansible/Python removal

roles/insights_client/files/insights.fact, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt
Few years ago, the `#!/bin/bash` shebang for bash scripts stopped to be allowed by ansible-test in favour of `#!/usr/bin/env bash` [1].
Hence, switch the fact script to `#!/usr/bin/env bash`, which will behave in the same way. This makes it possible to drop the ignores for this failure.
[1] https://github.com/ansible/ansible/pull/50954
=> fix: set a bash shebang recognized by ansible-test

docs/create_docs.yml, plugins/inventory/insights.py, plugins/modules/insights_config.py, plugins/modules/insights_register.py, release.yml, roles/compliance/tasks/install.yml, roles/compliance/tasks/run.yml, roles/insights_client/handlers/main.yml
This is a second round of fixes for `ansible-lint`; this includes:
- setting permissions for `template` outputs
- adding `changed_when` to `command` modules that do not create files
- a `noqa` exclude for a known/wanted situation
- improvements to the examples of the plugins
There should be no behaviour changes.
The documentation will be regenerated later on, before the next tagging.
=> ansible-lint lint fixes #2

docs/create_docs.yml, release.yml, roles/compliance/tasks/install.yml, roles/compliance/tasks/main.yml, roles/compliance/tasks/run.yml, roles/compliance/tests/compliance.yml, roles/compliance/tests/install-only.yml, roles/compliance/tests/run-only.yml, roles/insights_client/handlers/main.yml, roles/insights_client/tasks/main.yml, roles/insights_client/tests/example-insights-client-playbook.yml
Invoke the builtin modules (i.e. those shipped in ansible-core) using their FQCN, as recommended when using newer Ansible version with no need to support very old ones.
Do the same also for a local example.
=> FQCN fixes

release.yml, roles/insights_client/tests/example-insights-client-playbook.yml
The release playbook has a logic to replace the collection name depending on the parameters (the namespace and the name); this logic had few issues:
- copy&paste approach for the places where it was set
- a wrong collection name in one place, so it was not set as needed
- more places in which the collection name needs to be set set
This fixes the aforementioned issues. The list of places where to set the collection name is still a fixed list, however it should be easier to maintain now, and it rarely changes.
=> Fix replacing the collection name on release

.ansible-lint, .ansible-lint-ignore, .github/workflows/ansible-lint.yml
Introduce ansible-lint as proper check in GitHub Actions:
- add a simple config to reflect the current state
- add an override for a known situation
Sadly currently (ansible-lint v6.22.0) the action does not respect its `working_directory` for all the steps, failing in its initial setup steps; a potential fix has been proposed [1], so create a local workaround to get the action to run in the meanwhile.
[1] https://github.com/ansible/ansible-lint/pull/3905
=> Add ansible-lint

CHANGELOG.md, plugins/inventory/insights.py
Luckly the API we use is compatible, so there are no changes required, other than the version bump.
The only changes in the results are some different properties in the `<vars_prefix>patching` variable set for each host.
=> inventory: switch to v3 of the patch service

plugins/modules/insights_register.py
Hello,
I seem to have encountered and hopefully solved a small but impactful bug. The insights_register module registration wasn't able to complete registration at all on my clean RHEL 9.3 system on my first shot trying it. This seems to be because the '--register' parameter is passed as a string to the .extend function of the `register_args` list on line 140 rather than as a list:
https://github.com/RedHatInsights/ansible-collections-insights/blob/22dfe8e8cd69f0ab6378732678a3e9b1db6f8866/plugins/modules/insights_register.py#L140
This results in the unexpected behavior of passing each character in the string as an individual argument, spacing them out on the command line in the background. Unfortunately this fails silently, producing messages as though it worked from the ansible …
=> Fix bug preventing registration from working as expected

.ansible-lint-ignore, plugins/inventory/insights.py
Having multiple examples for an inventory plugin in a single "example" block is not seen nicely by ansible-lint: using an inventory plugin means top-level YAML keys, so multiple examples will trigger duplicate YAML keys.
Thus tweak the example to be a single example, with different sections for the various parts; add a small section for the authentication.
The changes make it possible to drop the override for the ansible-lint issue.
=> doc: improve example of inventory plugin

CHANGELOG.md, plugins/modules/insights_register.py
In case `force_reregister` is used, properly invoke `insights-client --unregister` as list command line arguments, so it actually works.
=> insights_register: fix insights-client unregistration on force

CHANGELOG.md, plugins/inventory/insights.py
Explicitly setting values means they will be passed in queries to Inventory, filtering the results. The problem is that, in case new types of staleness are added to Inventory, they will not be returned by default, whereas default behaviour is to return the hosts with all the types of staleness.
Since:
- Inventory does not do any filter if no staleness query arguments are passed
- an empty list of values for "staleness" already implies none are passed in the requests to Inventory
then change the default value of the "staleness" option to the empty list.
=> inventory: fix default of "staleness" option

CHANGELOG.md, roles/compliance/README.md, roles/compliance/tasks/main.yml
Manually check the Insights registration status using `insights-client`, rather than relying on a fact exported by the `insights_client` role. That fact alone does not guarantee that the system is registered, as the `machine-id` file may be on the system even after failed registration attempts.
Bonus point: this makes it possible to use the `compliance` role without the `insights_client` role, as long as something else takes care of registering the system using `insights-client`. Mention the `rhc` role as potential alternative.
=> compliance: manually check insights-client status

release.yml, roles/compliance/tasks/run.yml, roles/insights_client/handlers/main.yml
Switch all the usages of the `command` modules to the 'argv' syntax for specifying the command to run. While this syntax is more verbose and requires manually splitting a command, in practice has few advantages:
- it keeps command line invocations shorter and easier to read (IMHO), especially long ones
- there is no need to do quoting for arguments, especially in case of arguments with spaces (YAML quoting is still needed though)
- adding/removing parameters is easier, and their changes is easier to spot in diffs
There should be no behaviour change.
=> Use the 'argv' syntax for the 'command' usages

docs/templates/docs.md.j2, plugins/modules/insights_config.py, plugins/modules/insights_register.py
Running `insights-client` requires root permissions; add a note about it in the documentation of the `insights_config` and `insights_register` modules.
Extend the Markdown template for their documentation to output also the module notes.
The documentation will be regenerated before a new release; nevertheless, the result of this MR can be checked by running
```bash
$ cd docs && ansible-playbook create_docs.yml
```
=> Document root requirements for insights-client modules

.yamllint.yml, release.yml, roles/insights_client/tasks/main.yml
This PR deals with the remaining issues with long lines (i.e. longer than 80 characters), for which there are special bits in the yamllint configuration.
There only code change is the factoring of a filename in the `release.yml` as own fact, so there is less repetition and a shorter way to use it. Other than that, there are additional yamllint exclusions for `line-length` where it makes sense to keep long lines, and the removal of the special yamllint configuration bits.
=> Final changes for long lines

.github/workflows/ansible-lint.yml, .github/workflows/ansible-test.yml, .yamllint.yml, CHANGELOG.md, meta/runtime.yml, roles/compliance/tasks/install.yml, roles/insights_client/tasks/main.yml, tests/sanity/ignore-2.14.txt
- fix the CI `ansible-lint` job adding a workaround for a bug in the `ansible-lint` action
- allow the `yum` module for now, to support RHEL 7
- drop the yamllint configuration file, now empty
- bump the ansible requirement to 2.15, following the 2.14 EOL
See the messages of the individual commits for longer explanations.
=> ci/lint fixes; bump ansible to 2.15

CHANGELOG.md, roles/compliance/tasks/install.yml, roles/compliance/tasks/run.yml
This fixes the ability to run the role and install without privilege escalation at playbook level.
Obsoletes/replaces PRs #63 and #64, which saw no actions for quite some time.
=> fix: compliance: require priviledge escalation

.github/workflows/ansible-lint.yml
Due to recent changes in the ansible-lint action [1], the location of the output file download via wget is not correct. Hence, for now add a fake structure to work also with the paths 
calculated by the action.
Also, drop the old workaround, which is not needed anymore.
[1] https://github.com/ansible/ansible-lint/pull/4213
=> ci: add workaround for another ansible-lint action regression

plugins/inventory/insights.py
- the default number of hosts per request returned by Inventory is 50, with a current maximum of 100
- the default number of hosts per request returned by Patchman is 20, with a current maximum of 100
Hence bump both the limits to their maximum values, to reduce the number of requests.
There should be no behaviour change, as pagination is already handled.
=> inventory: bump Inventory and Patchman limits per requests

.github/workflows/ansible-test.yml
The collection namespace set in the sources is "redhat" already, and it is replaced with the proper one on release (or in general, when running the `release.yml` playbook manually).
If the collection namespace is taken from the GitHub owner of the repository for which the ansible-test workflow runs, then there will be a mismatch between what is set in `galaxy.yml` and what is found in the bits of the collection.
Hence, set the collection namespace to "redhat" when generating `galaxy.yml` to create the right source tree for ansible-test.
=> fix(ci): ansible-test: set the collection namespace to "redhat"

CHANGELOG.md, README.md, meta/runtime.yml, plugins/action/insights_config.py, plugins/modules/insights_config.py, plugins/modules/insights_register.py, release.yml, roles/insights_client/README.md, roles/insights_client/tasks/main.yml
Recent versions of the "rhc" Ansible system role, shipped as part of the Linux System Roles collection, provide the same amount of Red Hat Insights features as currently provided by the insights-client bits:
- the `insights_config` action/module
- the `insights_register` module
- the `insights_client` role
Since the "rhc" system role is the preferred solution for registration/connection to Red Hat Insights, formally deprecate all the insights-client bits, slating them for removal in the next major version (2.0.0).
The deprecation messages are emitted for each of the deprecated bit, and they are shown only if the deprecation messages are not explicitly disabled by the user. Since the name of the collection is now present in a couple of files, add them to the list of files in which update …
=> feat: deprecate insights-client modules & plugins

.github/workflows/codespell.yml
Add a simple workflow to run codespell on push and for pull requests. It uses the official action of the codespell project.
=> ci: add codespell workflow

.github/workflows/ansible-lint.yml, .github/workflows/ansible-test.yml, .github/workflows/codespell.yml, .github/workflows/galaxy-release.yml, .github/workflows/yamllint.yml
The GitHub workflows should not need any permission, not even read ones; hence explicitly disable all of them.
=> ci: disable all permissions for workflows
